keys:
  - &sylvain age1gvpuhzxqww0nzew24jhhg6vfj70whqydqv8jdf8dlyfl9hudsdesunlg4l
  - &sylvain_titan age1p60eunhppay73pkauhmkt828h2pzgcf4vsda9wx9zwrcjjzd6erqhnu4nw
  - &sylvain_hyperion age1rl0vzwefh2s4g0f49t320s8pf6dm82pp6ww9f3jks3z52y9mqsnq80wwuw
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - age:
      - *sylvain
      - *sylvain_titan
      - *sylvain_hyperion
