#!/usr/bin/env bash

set -euo pipefail

SCRIPTNAME=$(basename "$0")
RUNDIR=$(dirname "$(realpath $0)")
CURRENTDIR=$(pwd)
OUTPUTDIR=${CURRENTDIR}/out
SCRIPT_REQUIREMENTS=("jq" "yq")

mkdir -p $OUTPUTDIR

function _usage() {
	echo "USAGE"
	echo "${SCRIPTNAME} foo"
	echo "${SCRIPTNAME} bar aFile.json"
	exit 1
}

function _requirements() {
  inError=0
  for required in "${SCRIPT_REQUIREMENTS[@]}"; do
    if ! command -v ${required} &>/dev/null; then
      echo "${required} could not be found; please install it"
      inError=1
    fi
  done
  if [ $inError -eq 1 ];then exit 1; fi
}

function _checkCommand() {
	case ${1:-''} in
	completions) ;;
	foo) ;;
	bar) ;;
	*)
		_usage
		exit 1
		;;
	esac
}

function _checkArg() {
	if [ -z ${1:-''} ]; then
		_usage
		exit 1
	fi
}

function _ifEmpty() {
	if [ -z ${1:-''} ]; then
		"${@:2}"
	fi
}

function foo() {
	echo foo
}

function uuid() {
	cat /proc/sys/kernel/random/uuid
}

function bar() {
	_checkArg $1
	jq --unbuffered -c '.[]' $1 >$OUTPUTDIR/$1
}

_requirements
_checkCommand $@
$@
