# Auto-generated by compose2nix.
{ pkgs, lib, ... }:let
 appDir="/var/lib/frigate";
 storageDir="/data/disk1/frigate";

in {
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."frigate" = {
    image = "ghcr.io/blakeblackshear/frigate:stable";
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "${appDir}:/config:rw"
      "${storageDir}:/media/frigate:rw"
    ];
    ports = [
      "8971:8971/tcp"
      "8554:8554/tcp"
      "8555:8555/tcp"
      "8555:8555/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri/renderD128:/dev/dri/renderD128:rwm"
      "--network-alias=frigate"
      "--network=frigate_default"
      "--privileged"
      "--shm-size=536870912"
      "--tmpfs=/tmp/cache:size=1000000000"
    ];
  };
  systemd.services."docker-frigate" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-frigate_default.service"
    ];
    requires = [
      "docker-network-frigate_default.service"
    ];
    partOf = [
      "docker-compose-frigate-root.target"
    ];
    wantedBy = [
      "docker-compose-frigate-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-frigate_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f frigate_default";
    };
    script = ''
      docker network inspect frigate_default || docker network create frigate_default
    '';
    partOf = [ "docker-compose-frigate-root.target" ];
    wantedBy = [ "docker-compose-frigate-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-frigate-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
