#!/usr/bin/env bash

set -euo pipefail

SCRIPTNAME=$(basename "$0")

function _usage() {
  echo "USAGE"
  echo "${SCRIPTNAME} fetch_all [group_id]"
  echo "${SCRIPTNAME} filter_project [group_id] [branch_name]"
  echo "${SCRIPTNAME} delete_branch [project_id] [branch_name]"
  echo "${SCRIPTNAME} merge_mr [project_id] [branch_name]"
  echo "${SCRIPTNAME} list_all_mr_from_group [group_id] [target_branch]"
  exit 1
}

function _checkCommand() {
  case ${1:-''} in
  fetch_all) ;;
  filter_project) ;;
  delete_branch) ;;
  merge_mr) ;;
  list_all_mr_from_group) ;;
  *)
    _usage
    exit 1
    ;;
  esac
}

function _checkArg() {
  if [ -z ${1:-''} ]; then
    _usage
    exit 1
  fi
}
export -f _checkArg

function fetch_all() {
  _checkArg $1
  projects=$(mktemp)
  remotes=$(mktemp)
  glab api groups/$1/projects -X GET -f simple=true -f include_subgroups=true -f per_page=100 --paginate >$projects
  cat $projects | jq -r '.[]|.ssh_url_to_repo' >$remotes
  parallel ghq get {} <$remotes
}

function _filter_project() {
  _checkArg $1
  _checkArg $2
  local project=$1
  local branch=$(echo -n $2|jq -sRr @uri) #escape input for URI compliance
  if glab api "projects/$(echo ${project} | sed 's/\//%2F/g')/repository/branches/${branch}" &>/dev/null; then
    echo "$project"
  fi
}
export -f _filter_project

function filter_project() {
  _checkArg $1
  _checkArg $2
  projects_file=$(mktemp)
  groupId=$1
  branch=$2
  glab api groups/$1/projects -X GET -f simple=true -f include_subgroups=true -f per_page=100 --paginate | jq -r '.[] | .id' > $projects_file
  parallel _filter_project {} $branch <$projects_file
}

function delete_branch(){
  _checkArg $1
  _checkArg $2
  local projectId=$1
  local branch=$(echo -n $2|jq -sRr @uri) #escape input for URI compliance
  glab api -X DELETE --silent "/projects/$projectId/repository/branches/$branch"
}

function merge_mr(){
  _checkArg $1
  _checkArg $2
  local projectId=$1
  local mrId=$2
  glab api -X PUT --silent "/projects/${projectId}/merge_requests/${mrId}/merge"
}
export -f merge_mr

function list_all_mr_from_group(){
  _checkArg $1
  _checkArg $2
  local groupId=$1
  local targetBranch=$2
  glab mr list --target-branch=$targetBranch --group=$groupId --output=json|jq -r '.[]|"\(.project_id);\(.iid)"'
}

_checkCommand $@
$@
