{
 "title": "Fail2ban",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "prometheus" },
   { "name": "filterIp", "label": "Filtered IP" }
  ]
 },
 "panels": [
  {
   "title": "Fail2Ban Unbans (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "loki_process_custom_fail2ban_unbans_total",
     "legendFormat": "{{jail}} ({{ip}})"
    }
   ]
  },
  {
   "title": "Fail2Ban Bans (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "loki_process_custom_fail2ban_bans_total",
     "legendFormat": "{{jail}} ({{ip}})"
    }
   ]
  },
  {
   "title": "Banned",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(ip) (rate({service_name=\"fail2ban\"} |~ `.*Ban.*` | regexp `.*Ban\\s+(?P<ip>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}).*` [$__auto]))"
    }
   ]
  },
  {
   "title": "Banned logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"fail2ban\"} |~ `.*Ban.*`"
    }
   ]
  },
  {
   "title": "Unbanned logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"fail2ban\"} |~ `.*Unban.*`"
    }
   ]
  },
  {
   "title": "Filtered logs on ip",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"fail2ban\"} |~ `.*$filterIp.*`"
    }
   ]
  }
 ]
}