{
 "title": "User browse history",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Top Public IPs (2XX)",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (remote_addr) (count_over_time({filename=\"/var/log/nginx/json_access.log\"} | json | __error__=\"\" | remote_addr !~ \"^(10\\\\.|172\\\\.(1[6-9]|2[0-9]|3[0-1])\\\\.|192\\\\.168\\\\.|127\\\\.|10\\\\.9\\\\.)\\\\d{1,3}\\\\.\\\\d{1,3}\" | status =~ \"2..\" [$__interval]))",
     "legendFormat": "{{remote_addr status}}"
    }
   ]
  },
  {
   "title": "Top Public http_host (2XX)",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by (remote_addr,http_host) (count_over_time({filename=\"/var/log/nginx/json_access.log\"} | json | remote_addr !~ \"^(10\\\\.|172\\\\.(1[6-9]|2[0-9]|3[0-1])\\\\.|192\\\\.168\\\\.|127\\\\.|10\\\\.9\\\\.)\\\\d{1,3}\\\\.\\\\d{1,3}\"  | status =~ \"2..\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr,http_referer}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/nginx/json_access.log\"} | json | remote_addr !~ \"^(10\\\\.|172\\\\.(1[6-9]|2[0-9]|3[0-1])\\\\.|192\\\\.168\\\\.|127\\\\.|10\\\\.9\\\\.)\\\\d{1,3}\\\\.\\\\d{1,3}\"  | status =~ \"2..\" | __error__=\"\""
    }
   ]
  }
 ]
}