{
 "title": "Status",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "processes",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total,groupname)"
    }
   }
  ]
 },
 "panels": [
  { "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 } },
  { "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 } },
  { "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 } },
  { "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 } },
  { "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 } },
  {
   "title": "Flake revision match",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nixos_flake_revision_match", "legendFormat": "__auto" }
   ]
  },
  { "gridPos": { "h": 10, "w": 3, "x": 18, "y": 0 } },
  {
   "title": "Last deployed commit",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "pullix_last_deployment", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Remote Flake revision",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nixos_flake_remote_revision) by (revision)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed services",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"failed\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Running jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{ type=\"oneshot\",name=~\"restic.*\",state=\"activating\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{ type=\"oneshot\",name=~\"nh.*\",state=\"activating\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{ type=\"oneshot\",name=\"nixos-upgrade.service\",state=\"activating\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 } }
 ]
}