#!/usr/bin/env bash

#set -euxo pipefail
set -euo pipefail

SCRIPTNAME=$(basename "$0")
RUNDIR=$(dirname "$(realpath $0)")
CURRENTDIR=$(pwd)

function _usage() {
	echo "USAGE"
	echo "${SCRIPTNAME} [source DIR] [filter] [target DIR]"
	exit 1
}

if [ $# != 3 ]; then
	_usage
else
	sourceDir=$1
	filter=$2
	targetDir=$3
	files=$(find $sourceDir -type f -name "$filter" -printf '%p\n')
	while IFS= read -r file; do
		newLink=$(echo "$file" | sed -E "s|${sourceDir}\/(.*)|\1|gm")
		mkdirs=$(echo $newLink | sed -E "s|((.*\/)*)[^\/]*|\1|gm" | sed '/^$/d')
		mkdir -p $targetDir/$mkdirs
		ln $file $targetDir/$newLink
	done <<<"$files"
fi
