#!/usr/bin/env bash

SCRIPTNAME=$(basename "$0")
RUNDIR=$(dirname "$(realpath $0)")
CURRENTDIR=$(pwd)

function _usage() {
	echo "USAGE"
	echo "${SCRIPTNAME} [source dir] [target dir]"
	exit 1
}

function _checkArg() {
	if [ -z ${1:-''} ]; then
		_usage
		exit 1
	fi
}

function updateDir {
  _checkArg $1
  _checkArg $2
	xs=$(find $1 -type f -name '*' -print)
	ys=$(find $2 -type f -name '*' -print)

	fileXs=$(mktemp)
	fileYs=$(mktemp)
	printf "%s\n" "${xs[@]}" >$fileXs
	printf "%s\n" "${ys[@]}" >$fileYs

	sort $fileXs >${fileXs}_sorted
	sort $fileYs >${fileYs}_sorted

	comm -23 ${fileXs}_sorted ${fileYs}_sorted >${fileXs}_resultat

	while read -r ligne; do
		file=$(echo $ligne | sed -E 's/.*\/(.*)/\1/g')
		ln "$ligne" "$2/$file" || true
	done <"${fileXs}_resultat"
}

updateDir $@
