name: "Generate LXC containers"
on:
  push:
    branches:
      - main
      - "feat/**"

jobs:
  generate_shell_lxc_container:
    name: Generate Shell LXC container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Generate shell-rhea
        run: |
          nix build .#nixosConfigurations.shell-rhea.config.formats.proxmox-lxc
          mv result shell-rhea.tar.xz
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          path: shell-rhea.tar.xz
          name: shell-rhea.tar.xz
  generate_jellyfin_lxc_container:
    name: Generate Jellyfin LXC container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Generate jellyfin-rhea
        run: |
          nix build .#nixosConfigurations.jellyfin-rhea.config.formats.proxmox-lxc
          mv result jellyfin-rhea.tar.xz
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          path: jellyfin-rhea.tar.xz
          name: jellyfin-rhea.tar.xz
  generate_inputs_lxc_container:
    name: Generate Inputs LXC container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Generate inputs-rhea
        run: |
          nix build .#nixosConfigurations.inputs-rhea.config.formats.proxmox-lxc
          mv result inputs-rhea.tar.xz
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          path: inputs-rhea.tar.xz
          name: inputs-rhea.tar.xz
  release:
    name: Create Github release
    needs:
      [
        generate_jellyfin_lxc_container,
        generate_inputs_lxc_container,
        generate_shell_lxc_container,
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download archive
        uses: actions/download-artifact@v3
        with:
          path: ./assets/
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete latest --cleanup-tag --yes || true
          find ./assets -type f -print| xargs gh release create latest --title latest --generate-notes
