name: "Hyperion deployments"
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Test or Prod"
        required: true
        type: choice
        options:
          - Test
          - Prod
jobs:
  deploy-test-from-main:
    if: ${{ github.event.inputs.target == 'Test' }}
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_BROKEN: "1"
      NIXPKGS_ALLOW_UNFREE: "1"
      NIXPKGS_ALLOW_INSECURE: "1"
      NIX_CONFIG: |
        experimental-features = nix-command flakes
        access-tokens = github.com=${{ secrets.GH_TOKEN }}
      GIT_AUTHOR_NAME: github-actions[bot]
      GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
      GIT_COMMITTER_NAME: github-actions[bot]
      GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Setup hyperion/test branch
        run: |
          git remote remove origin
          git remote add origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch
          git checkout -b hyperion/test || git checkout hyperion/test
          git reset --hard origin/main
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Push force
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git hyperion/test --force
  deploy-prod-from-test:
    if: ${{ github.event.inputs.target == 'Prod' }}
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_BROKEN: "1"
      NIXPKGS_ALLOW_UNFREE: "1"
      NIXPKGS_ALLOW_INSECURE: "1"
      NIX_CONFIG: |
        experimental-features = nix-command flakes
        access-tokens = github.com=${{ secrets.GH_TOKEN }}
      GIT_AUTHOR_NAME: github-actions[bot]
      GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
      GIT_COMMITTER_NAME: github-actions[bot]
      GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Setup hyperion/test branch
        run: |
          git remote remove origin
          git remote add origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch
          git checkout -b hyperion/prod || git checkout hyperion/prod
          git reset --hard hyperion/test
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Push force
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run:
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git hyperion/prod --force
