name: "Update flake inputs"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5" # Every week on Friday.
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_BROKEN: "1"
      NIXPKGS_ALLOW_UNFREE: "1"
      NIXPKGS_ALLOW_INSECURE: "1"
      NIX_CONFIG: "experimental-features = nix-command flakes"
      GIT_AUTHOR_NAME: github-actions[bot]
      GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
      GIT_COMMITTER_NAME: github-actions[bot]
      GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: mount Nix store on larger partition
        # on the Linux runner `/` doesn't have enough space, but there's a `/mnt` which does.
        if: runner.os == 'Linux'
        run: |
          sudo mkdir /nix /mnt/nix
          sudo mount --bind /mnt/nix /nix
      - uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: scarisey-public
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Update flake inputs
        run: |
          nix flake update --commit-lock-file --accept-flake-config
      - name: Update Antora custom pkgs
        run: |
          pushd pkgs/antora
          ./update.sh
          popd
          git add pkgs/antora
          git commit -m "build(antora):automatic update" || true
      - name: Update Sops custom pkgs
        run: |
          nix run nixpkgs#nix-update -- sops-latest --flake
          git add pkgs/sops
          git commit -m "build(sops):automatic update" || true
      - name: Build the titan config
        run: |
          nix build --accept-flake-config .#nixosConfigurations.titan.config.system.build.toplevel && nix build --accept-flake-config .\#homeConfigurations.sylvain@titan.activationPackage
      - name: Build the hyperion config
        run: |
          nix build --accept-flake-config .#nixosConfigurations.hyperion.config.system.build.toplevel && nix build --accept-flake-config .\#homeConfigurations.sylvain@hyperion.activationPackage
      - name: Build the lscarisey config
        run: |
          nix build --accept-flake-config .\#homeConfigurations.sylvain@lscarisey.activationPackage
      - name: Push changes to remote
        run: |
          git remote remove origin
          git remote add origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --set-upstream origin main
